version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn --version
      
  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean
      - echo "Ejecutando pruebas unitarias..."
      - mvn test -B
      
  build:
    commands:
      - echo Build phase started...
      - mvn compile
      - mvn test
      - mvn package -DskipTests
      
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - target/*.jar
  name: finnancy-backend-artifact

reports:
  junit_reports:
    files:
      - "target/surefire-reports/TEST-*.xml"
    file-format: JUNIT
