version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn --version
      
  pre_build:
    commands:
      - echo Pre-build phase for testing...
      - mvn clean
      
  build:
    commands:
      - echo Running unit tests...
      - mvn test -B
      
artifacts:
  files:
    - target/surefire-reports/**/*

reports:
  junit_reports:
    files:
      - "target/surefire-reports/TEST-*.xml"
    file-format: JUNIT
