version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-21-amazon-corretto"
    MAVEN_HOME: "/usr/share/maven"
    MAVEN_CONFIG: "$HOME/.m2"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Entered the install phase...
      - echo Installing Maven...
      - mvn --version
      
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Cleaning previous builds...
      - mvn clean
      
  build:
    commands:
      - echo Entered the build phase...
      - echo Starting build on `date`
      - mvn compile
      - mvn test
      - mvn package -DskipTests
      
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
  name: finnancy-backend-$(date +%Y-%m-%d)