version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn --version
      
  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean
      
  build:
    commands:
      - echo Building and packaging application...
      - mvn compile
      - mvn package -DskipTests
      - mvn clean package -DskipTests
      
  post_build:
    commands:
      - echo Build completed successfully
      
artifacts:
  files:
    - target/*.jar
  name: finnancy-backend-artifact
  discard-paths: yes
  base-directory: target
